#### <div style="color:#0077b6; text-align:right">NAME : SANJHI JAIN</div>
#### <div style="color:#0077b6; text-align:right">ROLL NO : CSC/21/19</div>

## <span style="color:#4a4e69">PRACTICAL 02 </span>

#### <span style="color:#007f5f">Write programs in Python using NumPy library to do the following:</span>

In [2]:
# importing numpy library

import numpy as np

##### <span style="color:#003f88">a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis</span>

In [3]:
#creating random 2d array of size (4x3)

rd_array=np.random.randint(21,size=(4,3))

print("Random Integer array:")
print(rd_array)

Random Integer array:
[[ 1  4 10]
 [ 7 15  6]
 [16 18 17]
 [10 18 15]]


In [4]:
#calculating mean along second axis

array_mean=rd_array.mean(axis=1)
print("Mean along second axis : ",array_mean)

Mean along second axis :  [ 5.          9.33333333 17.         14.33333333]


In [5]:
#calculating standard deviation along second axis

array_standard_deviation=rd_array.std(axis=1)
print("Standard Deviation along second axis : ",array_standard_deviation)

Standard Deviation along second axis :  [3.74165739 4.02768199 0.81649658 3.29983165]


In [6]:
#calculating variance along second axis

array_variance=rd_array.var(axis=1)
print("variance along second axis : ",array_variance)

variance along second axis :  [14.         16.22222222  0.66666667 10.88888889]


##### <span style="color:#003f88">b.Get the indices of the sorted elements of a given array.</span>
##### <span style="color:#007f5f"> a. B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]</span>

In [7]:
#soretd indices 

B=np.array([56,48,22,41,78,91,24,46,8,33])
B.argsort()

array([8, 2, 6, 9, 3, 7, 1, 0, 4, 5], dtype=int64)

##### <span style="color:#003f88">c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of the array and then reshape it into nx m array, n and m are user inputs given at the run time.
</span>

In [8]:
#creating mxn array by user input

row=int(input("Enter number of rows(m) : "))
col=int(input("Enter number of column(n) : "))

#-------generating random 2d array--------------
user_array=np.random.randint(100,size=(row,col))

#-----------------------------------------------
print("===============================\n \t Random 2d array\n\n",user_array,"\n===============================")

print("Shape of the array : ",np.shape(user_array))

print("Type of the array  : ",type(user_array))

print("Data type of the array : ",user_array.dtype)

#-------------------------------------------------
print("\n\nReshaped array (n) x (m) : ",col," x ",row)
print(user_array.reshape(col,row))

Enter number of rows(m) :  5
Enter number of column(n) :  3


 	 Random 2d array

 [[51 44 72]
 [19 30 38]
 [71 80 96]
 [99 96 89]
 [94 46 68]] 
Shape of the array :  (5, 3)
Type of the array  :  <class 'numpy.ndarray'>
Data type of the array :  int32


Reshaped array (n) x (m) :  3  x  5
[[51 44 72 19 30]
 [38 71 80 96 99]
 [96 89 94 46 68]]


##### <span style="color:#003f88">d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of these elements in three separate arrays.
</span>

In [9]:
#--created a custom array 2d array--------
array = np.array([[1,2,0],[0,6,4],[np.nan,0,10],[20,np.nan,15]])
print(array)

[[ 1.  2.  0.]
 [ 0.  6.  4.]
 [nan  0. 10.]
 [20. nan 15.]]


In [10]:
#finding indices of NaN records
res= np.argwhere(np.isnan(array))
print(res)

[[2 0]
 [3 1]]


In [11]:
#finding indicies of zero elements in the array
res= np.argwhere(array==0)
print(res)

[[0 2]
 [1 0]
 [2 1]]


In [12]:
#finding indicies of nonzero elements in the array
res= np.argwhere(array)
print(res)

[[0 0]
 [0 1]
 [1 1]
 [1 2]
 [2 0]
 [2 2]
 [3 0]
 [3 1]
 [3 2]]
